# Generated by Django 5.1 on 2024-08-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olma_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
